/**
 * @module validation/areaCodes
 * @description North American Numbering Plan (NANP) Area Codes
 *   This file is auto-generated. Do not edit directly.
 *   To update, run the script at scripts/update-area-codes.js
 * @see {@link https://secure.nanpa.com/public-report/npa/geographic-use|NANPA}
 * @see {@link https://secure.nanpa.com/public-report/npa/nonGeographic-use|NANPA}

/**
 * @type {Array<{code: string, location: string, country: string}>}
 * @constant
 */
const areaCodes = [
  { code: '201', location: 'NJ', country : 'US' },
  { code: '202', location: 'DC', country : 'US' },
  { code: '203', location: 'CT', country : 'US' },
  { code: '204', location: 'MANITOBA', country : 'CA' },
  { code: '205', location: 'AL', country : 'US' },
  { code: '206', location: 'WA', country : 'US' },
  { code: '207', location: 'ME', country : 'US' },
  { code: '208', location: 'ID', country : 'US' },
  { code: '209', location: 'CA', country : 'US' },
  { code: '210', location: 'TX', country : 'US' },
  { code: '212', location: 'NY', country : 'US' },
  { code: '213', location: 'CA', country : 'US' },
  { code: '214', location: 'TX', country : 'US' },
  { code: '215', location: 'PA', country : 'US' },
  { code: '216', location: 'OH', country : 'US' },
  { code: '217', location: 'IL', country : 'US' },
  { code: '218', location: 'MN', country : 'US' },
  { code: '219', location: 'IN', country : 'US' },
  { code: '220', location: 'OH', country : 'US' },
  { code: '223', location: 'PA', country : 'US' },
  { code: '224', location: 'IL', country : 'US' },
  { code: '225', location: 'LA', country : 'US' },
  { code: '226', location: 'ONTARIO', country : 'CA' },
  { code: '227', location: 'MD', country : 'US' },
  { code: '228', location: 'MS', country : 'US' },
  { code: '229', location: 'GA', country : 'US' },
  { code: '231', location: 'MI', country : 'US' },
  { code: '234', location: 'OH', country : 'US' },
  { code: '235', location: 'MO', country : 'US' },
  { code: '236', location: 'BRITISH COLUMBIA', country : 'CA' },
  { code: '239', location: 'FL', country : 'US' },
  { code: '240', location: 'MD', country : 'US' },
  { code: '242', location: 'BAHAMAS', country : 'BS' },
  { code: '246', location: 'BARBADOS', country : 'BB' },
  { code: '248', location: 'MI', country : 'US' },
  { code: '249', location: 'ONTARIO', country : 'CA' },
  { code: '250', location: 'BRITISH COLUMBIA', country : 'CA' },
  { code: '251', location: 'AL', country : 'US' },
  { code: '252', location: 'NC', country : 'US' },
  { code: '253', location: 'WA', country : 'US' },
  { code: '254', location: 'TX', country : 'US' },
  { code: '256', location: 'AL', country : 'US' },
  { code: '257', location: 'BRITISH COLUMBIA', country : 'CA' },
  { code: '260', location: 'IN', country : 'US' },
  { code: '262', location: 'WI', country : 'US' },
  { code: '263', location: 'QUEBEC', country : 'CA' },
  { code: '264', location: 'ANGUILLA', country : 'AI' },
  { code: '267', location: 'PA', country : 'US' },
  { code: '268', location: 'ANTIGUA/BARBUDA', country : 'AG' },
  { code: '269', location: 'MI', country : 'US' },
  { code: '270', location: 'KY', country : 'US' },
  { code: '272', location: 'PA', country : 'US' },
  { code: '274', location: 'WI', country : 'US' },
  { code: '276', location: 'VA', country : 'US' },
  { code: '279', location: 'CA', country : 'US' },
  { code: '281', location: 'TX', country : 'US' },
  { code: '283', location: 'OH', country : 'US' },
  { code: '284', location: 'BRITISH VIRGIN ISLANDS', country : 'VG' },
  { code: '289', location: 'ONTARIO', country : 'CA' },
  { code: '301', location: 'MD', country : 'US' },
  { code: '302', location: 'DE', country : 'US' },
  { code: '303', location: 'CO', country : 'US' },
  { code: '304', location: 'WV', country : 'US' },
  { code: '305', location: 'FL', country : 'US' },
  { code: '306', location: 'SASKATCHEWAN', country : 'CA' },
  { code: '307', location: 'WY', country : 'US' },
  { code: '308', location: 'NE', country : 'US' },
  { code: '309', location: 'IL', country : 'US' },
  { code: '310', location: 'CA', country : 'US' },
  { code: '312', location: 'IL', country : 'US' },
  { code: '313', location: 'MI', country : 'US' },
  { code: '314', location: 'MO', country : 'US' },
  { code: '315', location: 'NY', country : 'US' },
  { code: '316', location: 'KS', country : 'US' },
  { code: '317', location: 'IN', country : 'US' },
  { code: '318', location: 'LA', country : 'US' },
  { code: '319', location: 'IA', country : 'US' },
  { code: '320', location: 'MN', country : 'US' },
  { code: '321', location: 'FL', country : 'US' },
  { code: '323', location: 'CA', country : 'US' },
  { code: '324', location: 'FL', country : 'US' },
  { code: '325', location: 'TX', country : 'US' },
  { code: '326', location: 'OH', country : 'US' },
  { code: '327', location: 'AR', country : 'US' },
  { code: '329', location: 'NY', country : 'US' },
  { code: '330', location: 'OH', country : 'US' },
  { code: '331', location: 'IL', country : 'US' },
  { code: '332', location: 'NY', country : 'US' },
  { code: '334', location: 'AL', country : 'US' },
  { code: '336', location: 'NC', country : 'US' },
  { code: '337', location: 'LA', country : 'US' },
  { code: '339', location: 'MA', country : 'US' },
  { code: '340', location: 'VI', country : 'US' },
  { code: '341', location: 'CA', country : 'US' },
  { code: '343', location: 'ONTARIO', country : 'CA' },
  { code: '345', location: 'CAYMAN ISLANDS', country : 'KY' },
  { code: '346', location: 'TX', country : 'US' },
  { code: '347', location: 'NY', country : 'US' },
  { code: '350', location: 'CA', country : 'US' },
  { code: '351', location: 'MA', country : 'US' },
  { code: '352', location: 'FL', country : 'US' },
  { code: '353', location: 'WI', country : 'US' },
  { code: '354', location: 'QUEBEC', country : 'CA' },
  { code: '357', location: 'CA', country : 'US' },
  { code: '360', location: 'WA', country : 'US' },
  { code: '361', location: 'TX', country : 'US' },
  { code: '363', location: 'NY', country : 'US' },
  { code: '364', location: 'KY', country : 'US' },
  { code: '365', location: 'ONTARIO', country : 'CA' },
  { code: '367', location: 'QUEBEC', country : 'CA' },
  { code: '368', location: 'ALBERTA', country : 'CA' },
  { code: '369', location: 'CA', country : 'US' },
  { code: '380', location: 'OH', country : 'US' },
  { code: '382', location: 'ONTARIO', country : 'CA' },
  { code: '385', location: 'UT', country : 'US' },
  { code: '386', location: 'FL', country : 'US' },
  { code: '401', location: 'RI', country : 'US' },
  { code: '402', location: 'NE', country : 'US' },
  { code: '403', location: 'ALBERTA', country : 'CA' },
  { code: '404', location: 'GA', country : 'US' },
  { code: '405', location: 'OK', country : 'US' },
  { code: '406', location: 'MT', country : 'US' },
  { code: '407', location: 'FL', country : 'US' },
  { code: '408', location: 'CA', country : 'US' },
  { code: '409', location: 'TX', country : 'US' },
  { code: '410', location: 'MD', country : 'US' },
  { code: '412', location: 'PA', country : 'US' },
  { code: '413', location: 'MA', country : 'US' },
  { code: '414', location: 'WI', country : 'US' },
  { code: '415', location: 'CA', country : 'US' },
  { code: '416', location: 'ONTARIO', country : 'CA' },
  { code: '417', location: 'MO', country : 'US' },
  { code: '418', location: 'QUEBEC', country : 'CA' },
  { code: '419', location: 'OH', country : 'US' },
  { code: '423', location: 'TN', country : 'US' },
  { code: '424', location: 'CA', country : 'US' },
  { code: '425', location: 'WA', country : 'US' },
  { code: '428', location: 'NEW BRUNSWICK', country : 'CA' },
  { code: '430', location: 'TX', country : 'US' },
  { code: '431', location: 'MANITOBA', country : 'CA' },
  { code: '432', location: 'TX', country : 'US' },
  { code: '434', location: 'VA', country : 'US' },
  { code: '435', location: 'UT', country : 'US' },
  { code: '436', location: 'OH', country : 'US' },
  { code: '437', location: 'ONTARIO', country : 'CA' },
  { code: '438', location: 'QUEBEC', country : 'CA' },
  { code: '440', location: 'OH', country : 'US' },
  { code: '441', location: 'BERMUDA', country : 'BM' },
  { code: '442', location: 'CA', country : 'US' },
  { code: '443', location: 'MD', country : 'US' },
  { code: '445', location: 'PA', country : 'US' },
  { code: '447', location: 'IL', country : 'US' },
  { code: '448', location: 'FL', country : 'US' },
  { code: '450', location: 'QUEBEC', country : 'CA' },
  { code: '457', location: 'LA', country : 'US' },
  { code: '458', location: 'OR', country : 'US' },
  { code: '463', location: 'IN', country : 'US' },
  { code: '464', location: 'IL', country : 'US' },
  { code: '468', location: 'QUEBEC', country : 'CA' },
  { code: '469', location: 'TX', country : 'US' },
  { code: '470', location: 'GA', country : 'US' },
  { code: '472', location: 'NC', country : 'US' },
  { code: '473', location: 'GRENADA', country : 'GD' },
  { code: '474', location: 'SASKATCHEWAN', country : 'CA' },
  { code: '475', location: 'CT', country : 'US' },
  { code: '478', location: 'GA', country : 'US' },
  { code: '479', location: 'AR', country : 'US' },
  { code: '480', location: 'AZ', country : 'US' },
  { code: '484', location: 'PA', country : 'US' },
  { code: '501', location: 'AR', country : 'US' },
  { code: '502', location: 'KY', country : 'US' },
  { code: '503', location: 'OR', country : 'US' },
  { code: '504', location: 'LA', country : 'US' },
  { code: '505', location: 'NM', country : 'US' },
  { code: '506', location: 'NEW BRUNSWICK', country : 'CA' },
  { code: '507', location: 'MN', country : 'US' },
  { code: '508', location: 'MA', country : 'US' },
  { code: '509', location: 'WA', country : 'US' },
  { code: '510', location: 'CA', country : 'US' },
  { code: '512', location: 'TX', country : 'US' },
  { code: '513', location: 'OH', country : 'US' },
  { code: '514', location: 'QUEBEC', country : 'CA' },
  { code: '515', location: 'IA', country : 'US' },
  { code: '516', location: 'NY', country : 'US' },
  { code: '517', location: 'MI', country : 'US' },
  { code: '518', location: 'NY', country : 'US' },
  { code: '519', location: 'ONTARIO', country : 'CA' },
  { code: '520', location: 'AZ', country : 'US' },
  { code: '530', location: 'CA', country : 'US' },
  { code: '531', location: 'NE', country : 'US' },
  { code: '534', location: 'WI', country : 'US' },
  { code: '539', location: 'OK', country : 'US' },
  { code: '540', location: 'VA', country : 'US' },
  { code: '541', location: 'OR', country : 'US' },
  { code: '548', location: 'ONTARIO', country : 'CA' },
  { code: '551', location: 'NJ', country : 'US' },
  { code: '557', location: 'MO', country : 'US' },
  { code: '559', location: 'CA', country : 'US' },
  { code: '561', location: 'FL', country : 'US' },
  { code: '562', location: 'CA', country : 'US' },
  { code: '563', location: 'IA', country : 'US' },
  { code: '564', location: 'WA', country : 'US' },
  { code: '567', location: 'OH', country : 'US' },
  { code: '570', location: 'PA', country : 'US' },
  { code: '571', location: 'VA', country : 'US' },
  { code: '572', location: 'OK', country : 'US' },
  { code: '573', location: 'MO', country : 'US' },
  { code: '574', location: 'IN', country : 'US' },
  { code: '575', location: 'NM', country : 'US' },
  { code: '579', location: 'QUEBEC', country : 'CA' },
  { code: '580', location: 'OK', country : 'US' },
  { code: '581', location: 'QUEBEC', country : 'CA' },
  { code: '582', location: 'PA', country : 'US' },
  { code: '584', location: 'MANITOBA', country : 'CA' },
  { code: '585', location: 'NY', country : 'US' },
  { code: '586', location: 'MI', country : 'US' },
  { code: '587', location: 'ALBERTA', country : 'CA' },
  { code: '601', location: 'MS', country : 'US' },
  { code: '602', location: 'AZ', country : 'US' },
  { code: '603', location: 'NH', country : 'US' },
  { code: '604', location: 'BRITISH COLUMBIA', country : 'CA' },
  { code: '605', location: 'SD', country : 'US' },
  { code: '606', location: 'KY', country : 'US' },
  { code: '607', location: 'NY', country : 'US' },
  { code: '608', location: 'WI', country : 'US' },
  { code: '609', location: 'NJ', country : 'US' },
  { code: '610', location: 'PA', country : 'US' },
  { code: '612', location: 'MN', country : 'US' },
  { code: '613', location: 'ONTARIO', country : 'CA' },
  { code: '614', location: 'OH', country : 'US' },
  { code: '615', location: 'TN', country : 'US' },
  { code: '616', location: 'MI', country : 'US' },
  { code: '617', location: 'MA', country : 'US' },
  { code: '618', location: 'IL', country : 'US' },
  { code: '619', location: 'CA', country : 'US' },
  { code: '620', location: 'KS', country : 'US' },
  { code: '621', location: 'TX', country : 'US' },
  { code: '623', location: 'AZ', country : 'US' },
  { code: '624', location: 'NY', country : 'US' },
  { code: '626', location: 'CA', country : 'US' },
  { code: '628', location: 'CA', country : 'US' },
  { code: '629', location: 'TN', country : 'US' },
  { code: '630', location: 'IL', country : 'US' },
  { code: '631', location: 'NY', country : 'US' },
  { code: '636', location: 'MO', country : 'US' },
  { code: '639', location: 'SASKATCHEWAN', country : 'CA' },
  { code: '640', location: 'NJ', country : 'US' },
  { code: '641', location: 'IA', country : 'US' },
  { code: '645', location: 'FL', country : 'US' },
  { code: '646', location: 'NY', country : 'US' },
  { code: '647', location: 'ONTARIO', country : 'CA' },
  { code: '649', location: 'TURKS & CAICOS ISLANDS', country : 'TC' },
  { code: '650', location: 'CA', country : 'US' },
  { code: '651', location: 'MN', country : 'US' },
  { code: '656', location: 'FL', country : 'US' },
  { code: '657', location: 'CA', country : 'US' },
  { code: '658', location: 'JAMAICA', country : 'JM' },
  { code: '659', location: 'AL', country : 'US' },
  { code: '660', location: 'MO', country : 'US' },
  { code: '661', location: 'CA', country : 'US' },
  { code: '662', location: 'MS', country : 'US' },
  { code: '664', location: 'MONTSERRAT', country : 'MS' },
  { code: '667', location: 'MD', country : 'US' },
  { code: '669', location: 'CA', country : 'US' },
  { code: '670', location: 'CNMI', country : 'MP' },
  { code: '671', location: 'GU', country : 'US' },
  { code: '672', location: 'BRITISH COLUMBIA', country : 'CA' },
  { code: '678', location: 'GA', country : 'US' },
  { code: '679', location: 'MI', country : 'US' },
  { code: '680', location: 'NY', country : 'US' },
  { code: '681', location: 'WV', country : 'US' },
  { code: '682', location: 'TX', country : 'US' },
  { code: '683', location: 'ONTARIO', country : 'CA' },
  { code: '684', location: 'AS', country : 'US' },
  { code: '686', location: 'VA', country : 'US' },
  { code: '689', location: 'FL', country : 'US' },
  { code: '701', location: 'ND', country : 'US' },
  { code: '702', location: 'NV', country : 'US' },
  { code: '703', location: 'VA', country : 'US' },
  { code: '704', location: 'NC', country : 'US' },
  { code: '705', location: 'ONTARIO', country : 'CA' },
  { code: '706', location: 'GA', country : 'US' },
  { code: '707', location: 'CA', country : 'US' },
  { code: '708', location: 'IL', country : 'US' },
  { code: '709', location: 'NEWFOUNDLAND AND LABRADOR', country : 'CA' },
  { code: '712', location: 'IA', country : 'US' },
  { code: '713', location: 'TX', country : 'US' },
  { code: '714', location: 'CA', country : 'US' },
  { code: '715', location: 'WI', country : 'US' },
  { code: '716', location: 'NY', country : 'US' },
  { code: '717', location: 'PA', country : 'US' },
  { code: '718', location: 'NY', country : 'US' },
  { code: '719', location: 'CO', country : 'US' },
  { code: '720', location: 'CO', country : 'US' },
  { code: '721', location: 'SINT MAARTEN', country : 'SX' },
  { code: '724', location: 'PA', country : 'US' },
  { code: '725', location: 'NV', country : 'US' },
  { code: '726', location: 'TX', country : 'US' },
  { code: '727', location: 'FL', country : 'US' },
  { code: '728', location: 'FL', country : 'US' },
  { code: '729', location: 'TN', country : 'US' },
  { code: '730', location: 'IL', country : 'US' },
  { code: '731', location: 'TN', country : 'US' },
  { code: '732', location: 'NJ', country : 'US' },
  { code: '734', location: 'MI', country : 'US' },
  { code: '737', location: 'TX', country : 'US' },
  { code: '738', location: 'CA', country : 'US' },
  { code: '740', location: 'OH', country : 'US' },
  { code: '742', location: 'ONTARIO', country : 'CA' },
  { code: '743', location: 'NC', country : 'US' },
  { code: '747', location: 'CA', country : 'US' },
  { code: '748', location: 'CO', country : 'US' },
  { code: '753', location: 'ONTARIO', country : 'CA' },
  { code: '754', location: 'FL', country : 'US' },
  { code: '757', location: 'VA', country : 'US' },
  { code: '758', location: 'ST. LUCIA', country : 'LC' },
  { code: '760', location: 'CA', country : 'US' },
  { code: '762', location: 'GA', country : 'US' },
  { code: '763', location: 'MN', country : 'US' },
  { code: '765', location: 'IN', country : 'US' },
  { code: '767', location: 'DOMINICA', country : 'DM' },
  { code: '769', location: 'MS', country : 'US' },
  { code: '770', location: 'GA', country : 'US' },
  { code: '771', location: 'DC', country : 'US' },
  { code: '772', location: 'FL', country : 'US' },
  { code: '773', location: 'IL', country : 'US' },
  { code: '774', location: 'MA', country : 'US' },
  { code: '775', location: 'NV', country : 'US' },
  { code: '778', location: 'BRITISH COLUMBIA', country : 'CA' },
  { code: '779', location: 'IL', country : 'US' },
  { code: '780', location: 'ALBERTA', country : 'CA' },
  { code: '781', location: 'MA', country : 'US' },
  { code: '782', location: 'NOVA SCOTIA - PRINCE EDWARD ISLAND', country : 'CA' },
  { code: '784', location: 'ST. VINCENT & GRENADINES', country : 'VC' },
  { code: '785', location: 'KS', country : 'US' },
  { code: '786', location: 'FL', country : 'US' },
  { code: '787', location: 'PR', country : 'US' },
  { code: '801', location: 'UT', country : 'US' },
  { code: '802', location: 'VT', country : 'US' },
  { code: '803', location: 'SC', country : 'US' },
  { code: '804', location: 'VA', country : 'US' },
  { code: '805', location: 'CA', country : 'US' },
  { code: '806', location: 'TX', country : 'US' },
  { code: '807', location: 'ONTARIO', country : 'CA' },
  { code: '808', location: 'HI', country : 'US' },
  { code: '809', location: 'DOMINICAN REPUBLIC', country : 'DO' },
  { code: '810', location: 'MI', country : 'US' },
  { code: '812', location: 'IN', country : 'US' },
  { code: '813', location: 'FL', country : 'US' },
  { code: '814', location: 'PA', country : 'US' },
  { code: '815', location: 'IL', country : 'US' },
  { code: '816', location: 'MO', country : 'US' },
  { code: '817', location: 'TX', country : 'US' },
  { code: '818', location: 'CA', country : 'US' },
  { code: '819', location: 'QUEBEC', country : 'CA' },
  { code: '820', location: 'CA', country : 'US' },
  { code: '821', location: 'SC', country : 'US' },
  { code: '825', location: 'ALBERTA', country : 'CA' },
  { code: '826', location: 'VA', country : 'US' },
  { code: '828', location: 'NC', country : 'US' },
  { code: '829', location: 'DOMINICAN REPUBLIC', country : 'DO' },
  { code: '830', location: 'TX', country : 'US' },
  { code: '831', location: 'CA', country : 'US' },
  { code: '832', location: 'TX', country : 'US' },
  { code: '835', location: 'PA', country : 'US' },
  { code: '837', location: 'CA', country : 'US' },
  { code: '838', location: 'NY', country : 'US' },
  { code: '839', location: 'SC', country : 'US' },
  { code: '840', location: 'CA', country : 'US' },
  { code: '843', location: 'SC', country : 'US' },
  { code: '845', location: 'NY', country : 'US' },
  { code: '847', location: 'IL', country : 'US' },
  { code: '848', location: 'NJ', country : 'US' },
  { code: '849', location: 'DOMINICAN REPUBLIC', country : 'DO' },
  { code: '850', location: 'FL', country : 'US' },
  { code: '854', location: 'SC', country : 'US' },
  { code: '856', location: 'NJ', country : 'US' },
  { code: '857', location: 'MA', country : 'US' },
  { code: '858', location: 'CA', country : 'US' },
  { code: '859', location: 'KY', country : 'US' },
  { code: '860', location: 'CT', country : 'US' },
  { code: '861', location: 'IL', country : 'US' },
  { code: '862', location: 'NJ', country : 'US' },
  { code: '863', location: 'FL', country : 'US' },
  { code: '864', location: 'SC', country : 'US' },
  { code: '865', location: 'TN', country : 'US' },
  { code: '867', location: 'NORTHWEST TERRITORIES -YUKON - NUNAVUT', country : 'CA' },
  { code: '868', location: 'TRINIDAD & TOBAGO', country : 'TT' },
  { code: '869', location: 'ST. KITTS & NEVIS', country : 'KN' },
  { code: '870', location: 'AR', country : 'US' },
  { code: '872', location: 'IL', country : 'US' },
  { code: '873', location: 'QUEBEC', country : 'CA' },
  { code: '876', location: 'JAMAICA', country : 'JM' },
  { code: '878', location: 'PA', country : 'US' },
  { code: '879', location: 'NEWFOUNDLAND AND LABRADOR', country : 'CA' },
  { code: '901', location: 'TN', country : 'US' },
  { code: '902', location: 'NOVA SCOTIA - PRINCE EDWARD ISLAND', country : 'CA' },
  { code: '903', location: 'TX', country : 'US' },
  { code: '904', location: 'FL', country : 'US' },
  { code: '905', location: 'ONTARIO', country : 'CA' },
  { code: '906', location: 'MI', country : 'US' },
  { code: '907', location: 'AK', country : 'US' },
  { code: '908', location: 'NJ', country : 'US' },
  { code: '909', location: 'CA', country : 'US' },
  { code: '910', location: 'NC', country : 'US' },
  { code: '912', location: 'GA', country : 'US' },
  { code: '913', location: 'KS', country : 'US' },
  { code: '914', location: 'NY', country : 'US' },
  { code: '915', location: 'TX', country : 'US' },
  { code: '916', location: 'CA', country : 'US' },
  { code: '917', location: 'NY', country : 'US' },
  { code: '918', location: 'OK', country : 'US' },
  { code: '919', location: 'NC', country : 'US' },
  { code: '920', location: 'WI', country : 'US' },
  { code: '924', location: 'MN', country : 'US' },
  { code: '925', location: 'CA', country : 'US' },
  { code: '928', location: 'AZ', country : 'US' },
  { code: '929', location: 'NY', country : 'US' },
  { code: '930', location: 'IN', country : 'US' },
  { code: '931', location: 'TN', country : 'US' },
  { code: '934', location: 'NY', country : 'US' },
  { code: '936', location: 'TX', country : 'US' },
  { code: '937', location: 'OH', country : 'US' },
  { code: '938', location: 'AL', country : 'US' },
  { code: '939', location: 'PR', country : 'US' },
  { code: '940', location: 'TX', country : 'US' },
  { code: '941', location: 'FL', country : 'US' },
  { code: '942', location: 'ONTARIO', country : 'CA' },
  { code: '943', location: 'GA', country : 'US' },
  { code: '945', location: 'TX', country : 'US' },
  { code: '947', location: 'MI', country : 'US' },
  { code: '948', location: 'VA', country : 'US' },
  { code: '949', location: 'CA', country : 'US' },
  { code: '951', location: 'CA', country : 'US' },
  { code: '952', location: 'MN', country : 'US' },
  { code: '954', location: 'FL', country : 'US' },
  { code: '956', location: 'TX', country : 'US' },
  { code: '959', location: 'CT', country : 'US' },
  { code: '970', location: 'CO', country : 'US' },
  { code: '971', location: 'OR', country : 'US' },
  { code: '972', location: 'TX', country : 'US' },
  { code: '973', location: 'NJ', country : 'US' },
  { code: '975', location: 'MO', country : 'US' },
  { code: '978', location: 'MA', country : 'US' },
  { code: '979', location: 'TX', country : 'US' },
  { code: '980', location: 'NC', country : 'US' },
  { code: '983', location: 'CO', country : 'US' },
  { code: '984', location: 'NC', country : 'US' },
  { code: '985', location: 'LA', country : 'US' },
  { code: '986', location: 'ID', country : 'US' },
  { code: '989', location: 'MI', country : 'US' },
  { code: '500', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '521', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '522', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '523', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '524', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '525', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '526', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '527', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '528', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '529', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '532', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '533', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '538', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '544', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '566', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '577', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '588', location: 'NON-GEOGRAPHIC SERVICES', country : 'US' },
  { code: '600', location: 'CANADIAN NON-GEOGRAPHIC TARIFFED SERVICES', country : 'CA' },
  { code: '622', location: 'CANADIAN NON-GEOGRAPHIC SERVICES', country : 'CA' },
  { code: '633', location: 'CANADIAN NON-GEOGRAPHIC SERVICES', country : 'CA' },
  { code: '700', location: 'INTEREXCHANGE CARRIER SERVICES', country : 'US' },
  { code: '710', location: 'US GOVERNMENT', country : 'US' },
  { code: '800', location: 'TOLL-FREE', country : 'US' },
  { code: '833', location: 'TOLL-FREE', country : 'US' },
  { code: '844', location: 'TOLL-FREE', country : 'US' },
  { code: '855', location: 'TOLL-FREE', country : 'US' },
  { code: '866', location: 'TOLL-FREE', country : 'US' },
  { code: '877', location: 'TOLL-FREE', country : 'US' },
  { code: '888', location: 'TOLL-FREE', country : 'US' },
  { code: '900', location: 'PREMIUM SERVICES', country : 'US' }
]
export { areaCodes }
